

# Configuration Nginx + PHP
web:
 restart: always
 image: nginx
 ports:
  - "80:80"
 volumes:
  - ./nginx:/etc/nginx/conf.d
  - ./www:/var/www/
 links:
  - php:php

php:
 build: php
 restart: always
 volumes:
  - ./www:/var/www/
  - ./php.ini:/usr/local/etc/php/php.ini
 links:
  - db:db
  - maildev:maildev
db:
 image: mysql
 restart: always
 ports: 
  - "3306:3306"
 volumes:
  - ./mysql/data:/var/lib/mysql
 environment:
  - MYSQL_ROOT_PASSWORD=root

maildev:
 restart: always
 image: djfarrelly/maildev
 ports:
  - "1080:80"
